using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace SmartApp.Util
{
    class JisUtil
    {
        public static String getJisByMunsell(String munsell)
        {
            Dictionary<String, String> jisHash = new Dictionary<String, String>();
            jisHash.Add("7RP 7.5/8", "とき色");
            jisHash.Add("7RP 5/13", "つつじ色");
            jisHash.Add("10RP 9/2.5", "桜色");
            jisHash.Add("1R 5/13", "ばら色");
            jisHash.Add("1.5R 5.5/13", "からくれない");
            jisHash.Add("2.5R 7/11", "さんご色");
            jisHash.Add("2.5R 6.5/7.5", "紅梅（こうばい）色");
            jisHash.Add("2.5R 6.5/8", "桃色");
            jisHash.Add("3R 4/14", "紅色");
            jisHash.Add("3.5R 4/13", "紅赤");
            jisHash.Add("4R 4/11", "えんじ");
            jisHash.Add("4R 4/7", "蘇芳（すおう）");
            //jisHash.Add("4R 3.5/11", "茜（あかね）色");
            jisHash.Add("4R 3.5/11", "赤");
            jisHash.Add("6R 5.5/14", "朱色");
            jisHash.Add("6R 4/8.5", "紅樺（べにかば）色");
            jisHash.Add("6.8R 5.5/14", "紅緋（べにひ）");
            jisHash.Add("7.5R 5/12", "鉛丹（えんたん）色");
            jisHash.Add("7.5R 3/5", "紅海老茶");
            jisHash.Add("7.5R 3.5/5", "とび色");
            jisHash.Add("8R 4.5/4.5", "小豆（あずき）色");
            jisHash.Add("8R 3.5/7", "弁柄（べんがら）色");
            jisHash.Add("8R 3/4.5", "海老茶");
            jisHash.Add("9R 5.5/14", "金赤");
            jisHash.Add("9R 3.5/8.5", "赤茶");
            //jisHash.Add("9R 3.5/8.5", "赤錆色");
            jisHash.Add("10R 6/12", "黄丹（おうに）");
            jisHash.Add("10R 5.5/14", "赤橙");
            jisHash.Add("10R 5.5/12", "柿色");
            jisHash.Add("10R 5.5/6", "肉桂（にっけい）色");
            jisHash.Add("10R 4.5/11", "樺（かば）色");
            jisHash.Add("10R 4/7", "れんが色");
            jisHash.Add("10R 3/3.5", "錆色");
            jisHash.Add("1YR 4.3/4", "檜皮（ひわだ）色");
            jisHash.Add("2YR 3.5/4", "栗色");
            jisHash.Add("2.5YR 5.5/13", "黄赤");
            jisHash.Add("2.5YR 5/8.5", "たいしゃ");
            jisHash.Add("4YR 5.5/6", "らくだ色");
            jisHash.Add("4YR 5/9", "黄茶");
            jisHash.Add("5YR 8/5", "肌色");
            jisHash.Add("5YR 6.5/13", "橙色");
            jisHash.Add("5YR 4.5/3", "灰茶");
            jisHash.Add("5YR 3.5/4", "茶色");
            jisHash.Add("5YR 3/2", "焦茶");
            jisHash.Add("5.5YR 7.5/9", "こうじ色");
            jisHash.Add("6YR 7/6", "杏色");
            jisHash.Add("6YR 6.5/13", "蜜柑色");
            jisHash.Add("6YR 3/7", "褐色");
            jisHash.Add("7.5YR 5/7", "土色");
            jisHash.Add("8YR 7/6", "小麦色");
            jisHash.Add("8YR 5.5/6.5", "こはく色");
            jisHash.Add("9YR 5.5/10", "金茶");
            jisHash.Add("10YR 8/7.5", "卵色");
            jisHash.Add("10YR 7.5/13", "山吹色");
            jisHash.Add("10YR 6/7.5", "黄土色");
            jisHash.Add("10YR 5/2", "朽葉（くちば）色");
            jisHash.Add("2Y 8/14", "ひまわり色");
            jisHash.Add("2Y 7.5/12", "うこん色");
            jisHash.Add("2.5Y 7.5/2", "砂色");
            jisHash.Add("3Y 7/6", "芥子（からし）色");
            jisHash.Add("5Y 8/14", "黄色");
            //jisHash.Add("5Y 8/14", "たんぽぽ色");
            jisHash.Add("5Y 4/3.5", "鶯茶");
            jisHash.Add("5Y 8.5/11", "中黄");
            jisHash.Add("7Y 8.5/7", "刈安（かりやす）色");
            jisHash.Add("9Y 8/8", "きはだ色");
            jisHash.Add("9.5Y 4.5/2.5", "みる色");
            jisHash.Add("1GY 7.5/8", "ひわ色");
            jisHash.Add("1GY 4.5/3.5", "鶯（うぐいす）色");
            jisHash.Add("2GY 7.5/4", "抹茶色");
            jisHash.Add("2.5GY 7.5/11", "黄緑");
            jisHash.Add("2.5GY 5/5", "苔色");
            jisHash.Add("3GY 7/10", "若草色");
            jisHash.Add("4GY 6.5/9", "萌黄（もえぎ）");
            jisHash.Add("5GY 5/5", "草色");
            jisHash.Add("7GY 7.5/4.5", "若葉色");
            jisHash.Add("7.5GY 5/4", "松葉色");
            jisHash.Add("2.5G 8.5/2.5", "白緑（びゃくろく）");
            jisHash.Add("2.5G 6.5/10", "緑");
            jisHash.Add("3G 4.5/7", "常磐（ときわ）色");
            jisHash.Add("4G 5/4", "緑青（ろくしょう）色");
            jisHash.Add("4G 4/3.5", "千歳緑（ちとせみどり）");
            jisHash.Add("5G 3/7", "深緑");
            jisHash.Add("5.5G 3/5", "もえぎ色");
            jisHash.Add("6G 6/7.5", "若竹色");
            jisHash.Add("7.5G 6.5/4", "青磁色");
            jisHash.Add("2.5BG 6.5/4", "青竹色");
            jisHash.Add("2.5BG 2.5/2.5", "鉄色");
            jisHash.Add("7.5BG 5/12", "青緑");
            jisHash.Add("10BG 5.5/3", "錆浅葱");
            jisHash.Add("1.5B 6/3", "水浅葱");
            jisHash.Add("2.5B 6.5/5.5", "新橋色");
            jisHash.Add("2.5B 5/8", "浅葱（あさぎ）色");
            jisHash.Add("3B 7/4.5", "白群（びゃくぐん）");
            jisHash.Add("4B 4/6", "納戸色");
            jisHash.Add("4.5B 7/4", "かめのぞき");
            jisHash.Add("6B 8/4", "水色");
            jisHash.Add("7.5B 4.5/2.5", "藍鼠（あいねず）");
            jisHash.Add("9B 7.5/5.5", "空色");
            jisHash.Add("10B 4/14", "青");
            jisHash.Add("2PB 3/5", "藍色");
            jisHash.Add("2PB 2/3.5", "濃藍（こいあい）");
            jisHash.Add("3PB 7/6", "勿忘草（わすれなぐさ）色");
            jisHash.Add("3PB 5/11", "露草色");
            jisHash.Add("3PB 4/7.5", "はなだ色");
            jisHash.Add("5PB 3/4", "紺青（こんじょう）");
            jisHash.Add("6PB 3.5/11", "るり色");
            jisHash.Add("6PB 3/8", "るり紺");
            jisHash.Add("6PB 2.5/4", "紺色");
            jisHash.Add("7PB 4/10", "かきつばた色");
            jisHash.Add("7PB 2.5/3", "勝色（かちいろ）");
            jisHash.Add("7.5PB 3.5/11", "群青（ぐんじょう）色");
            jisHash.Add("7.5PB 1.5/2", "鉄紺");
            jisHash.Add("9PB 4.5/7.5", "藤納戸");
            jisHash.Add("9PB 3.5/13", "ききょう色");
            jisHash.Add("9PB 2.5/9.5", "紺藍");
            jisHash.Add("10PB 6.5/6.5", "藤色");
            jisHash.Add("0.5P 6/9", "藤紫");
            jisHash.Add("2.5P 4/14", "青紫");
            jisHash.Add("2.5P 4/11", "菫（すみれ）色");
            jisHash.Add("2.5P 4/3.5", "鳩羽（はとば）色");
            //jisHash.Add("2.5P 4/3.5", "しょうぶ色");
            jisHash.Add("3P 3.5/7", "江戸紫");
            jisHash.Add("7.5P 5/12", "紫");
            jisHash.Add("7.5P 4/6", "古代紫");
            jisHash.Add("7.5P 2.5/2.5", "なす紺");
            jisHash.Add("8P 2/4", "紫紺");
            jisHash.Add("10P 6/10", "あやめ色");
            jisHash.Add("3RP 5/14", "牡丹（ぼたん）色");
            jisHash.Add("5RP 5.5/13", "赤紫");
            jisHash.Add("N9.5", "白");
            jisHash.Add("2.5Y 9.2/0.5", "胡粉（ごふん）色");
            jisHash.Add("10YR 9/1", "生成り（きなり）色");
            jisHash.Add("2.5Y 8.5/1.5", "象牙（ぞうげ）色");
            jisHash.Add("N6.5", "銀鼠（ぎんねず）");
            jisHash.Add("5YR 6/1", "茶鼠");
            jisHash.Add("N5.5", "鼠色");
            jisHash.Add("2.5G 5/1", "利休鼠");
            jisHash.Add("2.5PB 5/1", "鉛色");
            jisHash.Add("N5", "灰色");
            jisHash.Add("9.5YR 3.5/1.5", "すす竹色");
            jisHash.Add("2.5YR 2/1.5", "黒茶");
            jisHash.Add("N2", "墨");
            jisHash.Add("N1.5", "黒");
            //jisHash.Add("N1.5", "鉄黒");
            //jisHash.Add("-", "金色");
            //jisHash.Add("-", "銀色");
            jisHash.Add("7.5RP 5/12", "ローズレッド");
            jisHash.Add("10RP 7/8", "ローズピンク");
            jisHash.Add("10RP 4/12", "コチニールレッド");
            jisHash.Add("10RP 4/14", "ルビーレッド");
            jisHash.Add("10RP 3/9", "ワインレッド");
            jisHash.Add("10RP 2/2.5", "バーガンディー");
            jisHash.Add("1R 6/6.5", "オールドローズ");
            jisHash.Add("1R 5/14", "ローズ");
            jisHash.Add("1R 4/14", "ストロベリー");
            //jisHash.Add("2.5R 7/11", "コーラルレッド");
            jisHash.Add("2.5R 7/7", "ピンク");
            jisHash.Add("2.5R 2.5/3", "ボルドー");
            jisHash.Add("4R 8.5/4", "ベビーピンク");
            jisHash.Add("4R 5/14", "ポピーレッド");
            jisHash.Add("4R 4.5/14", "シグナルレッド");
            jisHash.Add("4R 4/14", "カーマイン");
            jisHash.Add("5R 5/14", "レッド");
            //jisHash.Add("5R 5/14", "トマトレッド");
            jisHash.Add("5R 2.5/6", "マルーン");
            //jisHash.Add("6R 5.5/14", "バーミリオン");
            jisHash.Add("7R 5/14", "スカーレット");
            jisHash.Add("7.5R 4.5/8", "テラコッタ");
            jisHash.Add("8R 7.5/7.5", "サーモンピンク");
            jisHash.Add("10R 8.5/3.5", "シェルピンク");
            jisHash.Add("10R 8/4", "ネールピンク");
            jisHash.Add("10R 6/15", "チャイニーズレッド");
            jisHash.Add("10R 5/11", "キャロットオレンジ");
            jisHash.Add("10R 4.5/7.5", "バーントシェンナ");
            jisHash.Add("10R 2.5/2.5", "チョコレート");
            //jisHash.Add("2YR 3.5/4", "ココアブラウン");
            jisHash.Add("3YR 8/3.5", "ピーチ");
            //jisHash.Add("4YR 5/9", "ローシェンナ");
            //jisHash.Add("5YR 6.5/13", "オレンジ");
            //jisHash.Add("5YR 3.5/4", "ブラウン");
            //jisHash.Add("6YR 7/6", "アプリコット");
            jisHash.Add("6YR 5/6", "タン");
            jisHash.Add("7YR 7/11.5", "マンダリンオレンジ");
            jisHash.Add("7YR 5.5/4", "コルク");
            jisHash.Add("7.5YR 8.5/4", "エクルベイジュ");
            jisHash.Add("7.5YR 7/10", "ゴールデンイエロー");
            jisHash.Add("8YR 7.5/13", "マリーゴールド");
            jisHash.Add("8YR 6.5/5", "バフ");
            //jisHash.Add("8YR 5.5/6.5", "アンバー");
            jisHash.Add("8.5YR 4/5", "ブロンズ");
            jisHash.Add("10YR 7/2.5", "ベージュ");
            //jisHash.Add("10YR 6/7.5", "イエローオーカー");
            jisHash.Add("10YR 3/3", "バーントアンバー");
            jisHash.Add("10YR 2.5/2", "セピア");
            jisHash.Add("1Y 5/5.5", "カーキー");
            jisHash.Add("2Y 7.5/7", "ブロンド");
            jisHash.Add("2.5Y 8/7.5", "ネープルスイエロー");
            jisHash.Add("2.5Y 8/4", "レグホーン");
            jisHash.Add("2.5Y 4/6", "ローアンバー");
            jisHash.Add("3Y 8/12", "クロムイエロー");
            jisHash.Add("5Y 8.5/14", "イエロー");
            jisHash.Add("5Y 8.5/3.5", "クリームイエロー");
            //jisHash.Add("5Y 8.5/14", "ジョンブリアン");
            jisHash.Add("7Y 8.5/10", "カナリヤ");
            jisHash.Add("7.5Y 4/2", "オリーブドラブ");
            jisHash.Add("7.5Y 3.5/4", "オリーブ");
            jisHash.Add("8Y 8/12", "レモンイエロー");
            jisHash.Add("2.5GY 3.5/3", "オリーブグリーン");
            jisHash.Add("4GY 8/10", "シャトルーズグリーン");
            jisHash.Add("5GY 6/7", "リーフグリーン");
            //jisHash.Add("5GY 5/5", "グラスグリーン");
            jisHash.Add("6GY 7/8", "シーグリーン");
            jisHash.Add("7.5GY 4/5", "アイビーグリーン");
            jisHash.Add("10GY 8/5", "アップルグリーン");
            jisHash.Add("2.5G 7.5/8", "ミントグリーン");
            jisHash.Add("2.5G 5.5/10", "グリーン");
            jisHash.Add("4G 7/9", "コバルトグリーン");
            jisHash.Add("4G 6/8", "エメラルドグリーン");
            jisHash.Add("4G 4.5/9", "マラカイトグリーン");
            jisHash.Add("5G 2.5/3", "ボトルグリーン");
            jisHash.Add("7.5G 4.5/5", "フォレストグリーン");
            jisHash.Add("8G 4/6", "ビリジアン");
            jisHash.Add("10G 2.5/5", "ビリヤードグリーン");
            jisHash.Add("7.5BG 4.5/9", "ピーコックグリーン");
            jisHash.Add("10BG 5.5/5", "ナイルブルー");
            jisHash.Add("10BG 4/8.5", "ピーコックブルー");
            jisHash.Add("5B 6/8", "ターコイズブルー");
            jisHash.Add("5B 3/7", "マリンブルー");
            jisHash.Add("7.5B 7/4", "ホリゾンブルー");
            jisHash.Add("7.5B 6/10", "シアン");
            //jisHash.Add("9B 7.5/5.5", "スカイブルー");
            jisHash.Add("9B 4.5/9", "セルリアンブルー");
            jisHash.Add("10B 7.5/3", "ベビーブルー");
            jisHash.Add("1PB 5/4.5", "サックスブルー");
            jisHash.Add("2.5PB 4.5/10", "ブルー");
            jisHash.Add("3PB 4/10", "コバルトブルー");
            //jisHash.Add("5PB 3/4", "アイアンブルー");
            //jisHash.Add("5PB 3/4", "プルシャンブルー");
            //jisHash.Add("5PB 3/4", "ミッドナイトブルー");
            jisHash.Add("5.5PB 5.5/6", "ヒヤシンス");
            //jisHash.Add("6PB 2.5/4", "ネービーブルー");
            //jisHash.Add("7.5PB 3.5/11", "ウルトラマリンブルー");
            jisHash.Add("7.5PB 3/10", "オリエンタルブルー");
            jisHash.Add("10PB 5/12", "ウィスタリア");
            jisHash.Add("1P 2.5/10", "パンジー");
            jisHash.Add("2P 5/10.5", "ヘリオトロープ");
            //jisHash.Add("2.5P 4/11", "バイオレット");
            jisHash.Add("5P 6/3", "ラベンダー");
            jisHash.Add("5P 4.5/9", "モーブ");
            jisHash.Add("6P 7/6", "ライラック");
            jisHash.Add("7.5P 7/6", "オーキッド");
            //jisHash.Add("7.5P 5/12", "パープル");
            jisHash.Add("5RP 5/14", "マゼンタ");
            jisHash.Add("6RP 5.5/11.5", "チェリーピンク");
            //jisHash.Add("N9.5", "ホワイト");
            //jisHash.Add("N9.5", "スノーホワイト");
            //jisHash.Add("2.5Y 8.5/1.5", "アイボリー");
            jisHash.Add("7.5B 7.5/0.5", "スカイグレイ");
            jisHash.Add("N7", "パールグレイ");
            //jisHash.Add("N6.5", "シルバーグレイ");
            jisHash.Add("N6", "アッシュグレイ");
            jisHash.Add("2.5R 5.5/1", "ローズグレイ");
            //jisHash.Add("N5", "グレイ");
            jisHash.Add("5P 4.5/1", "スチールグレイ");
            jisHash.Add("2.5PB 3.5/0.5", "スレートグレイ");
            jisHash.Add("5P 3/1", "チャコールグレイ");
            //jisHash.Add("N1", "ランプブラック");
            jisHash.Add("N1", "ブラック");

            if (jisHash.ContainsKey(munsell))
            {
                return jisHash[munsell];
            }
            else
            {
                return "非JIS慣用色";
            }
        }
    }
}
